"""PDF Generation Engine for Astra — Capacity Connect.
Turns educational text, study notes, flashcards, and lesson summaries into downloadable, beautifully formatted PDFs.
Supports:
1. External PDF Generation API via BYNARA_PDF_KEY
2. Built-in high-precision ReportLab PDF layout generator with modern educational styling
"""

import os
import io
import re
import time
import json
import uuid
import urllib.request
import urllib.error
from config import BYNARA_PDF_KEY, BYNARA_API_KEY, BYNARA_BACKUP_KEY

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas

if os.environ.get("VERCEL"):
    PDF_DIR = "/tmp/pdfs"
    os.makedirs(PDF_DIR, exist_ok=True)
else:
    PDF_DIR = os.path.join(os.path.dirname(__file__), "static", "pdfs")
    try:
        os.makedirs(PDF_DIR, exist_ok=True)
    except Exception:
        PDF_DIR = "/tmp/pdfs"
        os.makedirs(PDF_DIR, exist_ok=True)

KEYS = [k for k in [
    BYNARA_PDF_KEY,
    BYNARA_API_KEY,
    BYNARA_BACKUP_KEY
] if k and isinstance(k, str) and k.strip()]


class NumberedCanvas(canvas.Canvas):
    """Canvas that adds clean page numbers and headers/footers dynamically."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Footer
        footer_text = "Capacity Connect — AI Learning Operating System | Generated by Sastra AI"
        self.drawString(54, 30, footer_text)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 54, 30, page_str)

        # Thin footer line
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(54, 42, letter[0] - 54, 42)

        self.restoreState()


class PDFGenerator:
    """Multi-provider PDF synthesis engine."""

    def __init__(self):
        self.keys = [k for k in KEYS if k]

    def generate_pdf_from_text(self, text, title="Sastra Study Guide", topic="General Learning", author="Sastra AI"):
        """Generate a downloadable PDF from text/markdown with fallback."""
        author = str(author or "Sastra AI").replace("— Govt of Odisha", "").replace("- Govt of Odisha", "").replace("Govt of Odisha", "").strip() or "Sastra AI"
        clean_title = re.sub(r'[^a-zA-Z0-9_\- ]', '', title).strip() or "Study_Guide"
        file_id = f"{clean_title.replace(' ', '_')[:30]}_{uuid.uuid4().hex[:8]}.pdf"
        output_path = os.path.join(PDF_DIR, file_id)

        # Attempt Bynara PDF API if online
        for key in self.keys:
            try:
                api_url = "https://api-images.bynara.id/v1/pdf/generate"
                payload = {
                    "text": text,
                    "title": title,
                    "topic": topic,
                    "author": author
                }
                req = urllib.request.Request(
                    api_url,
                    data=json.dumps(payload).encode("utf-8"),
                    headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
                    method="POST"
                )
                with urllib.request.urlopen(req, timeout=8) as resp:
                    res = json.loads(resp.read().decode("utf-8"))
                    if res.get("pdf_url"):
                        return {
                            "url": res["pdf_url"],
                            "filename": file_id,
                            "title": title,
                            "pages": res.get("pages", 1)
                        }
            except Exception:
                # Fallback to internal ReportLab generator
                pass

        # Native ReportLab Styling Generator
        self._build_reportlab_pdf(text, title, topic, author, output_path)

        data_uri = ""
        try:
            import base64
            with open(output_path, "rb") as f:
                pdf_bytes = f.read()
                b64 = base64.b64encode(pdf_bytes).decode("utf-8")
                data_uri = f"data:application/pdf;base64,{b64}"
        except Exception:
            pass

        return {
            "url": f"/static/pdfs/{file_id}",
            "filename": file_id,
            "title": title,
            "local_path": output_path,
            "data_uri": data_uri
        }

    def _build_reportlab_pdf(self, markdown_text, title, topic, author, output_path):
        """Construct a high-definition, professionally styled educational PDF document."""
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        # Custom Palette
        c_navy = colors.HexColor("#0a152d")
        c_blue = colors.HexColor("#2563eb")
        c_dark = colors.HexColor("#1e293b")
        c_muted = colors.HexColor("#64748b")
        c_bg_box = colors.HexColor("#f8fafc")
        c_border = colors.HexColor("#e2e8f0")

        # Custom Typographic Styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=c_navy,
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=c_muted,
            spaceAfter=12
        )
        h1_style = ParagraphStyle(
            "H1",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=c_navy,
            spaceBefore=14,
            spaceAfter=6
        )
        h2_style = ParagraphStyle(
            "H2",
            parent=styles["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=15,
            textColor=c_blue,
            spaceBefore=10,
            spaceAfter=4
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14,
            textColor=c_dark,
            spaceAfter=6
        )
        bullet_style = ParagraphStyle(
            "Bullet",
            parent=body_style,
            leftIndent=14,
            firstLineIndent=-10,
            spaceAfter=4
        )
        code_style = ParagraphStyle(
            "CodeBlock",
            parent=styles["Normal"],
            fontName="Courier",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=4
        )

        story = []

        # Top Header Brand Bar
        header_table_data = [
            [
                Paragraph("<b>CAPACITY CONNECT</b> &nbsp;|&nbsp; AI LEARNING OPERATING SYSTEM", ParagraphStyle("Brand", fontName="Helvetica-Bold", fontSize=8, textColor=colors.HexColor("#3b82f6"))),
                Paragraph("SASTRA STUDY GUIDE", ParagraphStyle("Govt", fontName="Helvetica-Bold", fontSize=8, alignment=2, textColor=colors.HexColor("#2563eb")))
            ]
        ]
        t = Table(header_table_data, colWidths=[360, 144])
        t.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        story.append(t)
        story.append(Spacer(1, 6))
        story.append(HRFlowable(width="100%", thickness=1, color=c_border, spaceBefore=2, spaceAfter=14))

        # Title & Meta Section
        story.append(Paragraph(title, title_style))
        date_str = time.strftime("%B %d, %Y")
        meta_line = f"<b>Topic:</b> {topic} &nbsp;•&nbsp; <b>Author:</b> {author} &nbsp;•&nbsp; <b>Date:</b> {date_str} &nbsp;•&nbsp; <b>Verified:</b> Capacity Connect Curriculum"
        story.append(Paragraph(meta_line, subtitle_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=c_border, spaceBefore=4, spaceAfter=14))

        # Parse Markdown lines into styled elements
        lines = markdown_text.split("\n")
        in_code_block = False
        code_buffer = []

        for raw_line in lines:
            line = raw_line.strip()

            if line.startswith("```"):
                if in_code_block:
                    # Flush code block
                    code_text = "<br/>".join([c.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") for c in code_buffer])
                    code_p = Paragraph(code_text, code_style)
                    code_box = Table([[code_p]], colWidths=[504])
                    code_box.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f1f5f9")),
                        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                        ('PADDING', (0, 0), (-1, -1), 8),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                    ]))
                    story.append(code_box)
                    story.append(Spacer(1, 6))
                    code_buffer = []
                    in_code_block = False
                else:
                    in_code_block = True
                    code_buffer = []
                continue

            if in_code_block:
                code_buffer.append(raw_line)
                continue

            if not line:
                story.append(Spacer(1, 4))
                continue

            # Section Headers
            if line.startswith("# ") or line.startswith("## ") or line.startswith("✦ ") or line.startswith("🎬 ") or line.startswith("🧠 "):
                h_text = line.lstrip("#✦🎬🧠 ").strip()
                story.append(Paragraph(f"<b>{h_text}</b>", h1_style))
                story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceBefore=2, spaceAfter=6))
            elif line.startswith("### ") or line.startswith("◈ ") or line.startswith("❖ "):
                h_text = line.lstrip("#◈❖ ").strip()
                story.append(Paragraph(f"<b>{h_text}</b>", h2_style))
            elif line.startswith("- ") or line.startswith("* ") or line.startswith("❯ "):
                b_text = line.lstrip("-*❯ ").strip()
                b_formatted = self._format_inline_markdown(b_text)
                story.append(Paragraph(f"• &nbsp; {b_formatted}", bullet_style))
            elif re.match(r'^\d+\.\s', line):
                num_text = re.sub(r'^\d+\.\s', '', line)
                b_formatted = self._format_inline_markdown(num_text)
                story.append(Paragraph(f"<b>{line.split('.')[0]}.</b> &nbsp; {b_formatted}", bullet_style))
            else:
                p_formatted = self._format_inline_markdown(line)
                story.append(Paragraph(p_formatted, body_style))

        # Build document with Numbered Canvas
        doc.build(story, canvasmaker=NumberedCanvas)

    def _format_inline_markdown(self, text):
        """Convert markdown bold/italic/code syntax to ReportLab XML tags."""
        text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
        text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
        text = re.sub(r'`(.+?)`', r'<font name="Courier" color="#1e293b">\1</font>', text)
        return text


_pdf_gen_instance = None

def get_pdf_generator():
    """Singleton getter for PDFGenerator."""
    global _pdf_gen_instance
    if _pdf_gen_instance is None:
        _pdf_gen_instance = PDFGenerator()
    return _pdf_gen_instance
